install ack
install archey
install cowsay
install ctags
install curl
install git
install go
install heroku-toolbelt
install keychain
install openssh
install reattach-to-user-namespace
install rkhunter
install sloccount
install the_silver_searcher
install tmux
install tree
install vim
install wget
install zsh
install homebrew/versions/lua52
install luarocks --with-lua52
