#!/bin/sh
# Thanks: https://github.com/bolorino/dotfiles

NORMIFS=$IFS
RESET="%{F-}%{B-}"

bspc control --subscribe | while read -r line; do
	IFS=":"
	set -- ${line#?}
	while [ $# -gt 0 ]; do
		item=$1
		case $item in
			[OoFfUu]*)
				name=" ${item#?} "
				case $item in
					O*) printf "%s" "%{F#ff1e1e1e}%{B#ff8f9d6a}$name$RESET" ;; # focused occupied
					F*) printf "%s" "%{F#ff1e1e1e}%{B#ff8f9d6a}$name$RESET" ;; # focused free
					U*) printf "%s" "%{F#ffcf6a4c}%{B#ff8f9d6a}$name$RESET" ;; # focused urgent
					o*) printf "%s" "%{F#ff888888}$name$RESET" ;; # occupied
					f*) printf "%s" "%{F#ff555555}$name$RESET" ;; # free
					u*) printf "%s" "%{F#ffcf6a4c}$name$RESET" ;; # urgent
				esac ;;
			L*) printf "\n" ;;
		esac
		shift
	done
	IFS=$NORMIFS
done
