#!/bin/sh
# Thanks: https://github.com/bolorino/dotfiles

NORMIFS=$IFS

bspc control --subscribe | while read -r line; do
	IFS=":"
	set -- ${line#?}
	while [ $# -gt 0 ]; do
		item=$1
		case $item in
			[OoFfUu]*)
				name=" ${item#?} "
				case $item in
					O*) printf "%s" "<fc=#1e1e1e,#8f9d6a>$name</fc> " ;; # focused occupied
					F*) printf "%s" "<fc=#1e1e1e,#8f9d6a>$name</fc> " ;; # focused free
					U*) printf "%s" "<fc=#cf6a4c,#8f9d6a>$name</fc> " ;; # focused urgent
					o*) printf "%s" "<fc=#dddddd>$name</fc> " ;; # occupied
					f*) printf "%s" "<fc=#555555>$name</fc> " ;; # free
					u*) printf "%s" "<fc=#cf6a4c>$name</fc> " ;; # urgent
				esac ;;
			L*) printf "\n" ;;
		esac
		shift
	done
	IFS=$NORMIFS
done
