#!/bin/sh

bspc config border_width        2
bspc config window_gap          10
bspc config top_padding         20

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d α β γ δ ε ζ η θ ι κ λ # μ ν ξ ο π ρ ς σ τ υ φ χ ψ ω

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a gromit-mpx manage=off
bspc rule -a stalonetray manage=off

~/.config/bspwm/bspwmbar | xmobar &
