#!/bin/sh

bspc config border_width        2
bspc config window_gap          10

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config remove_unplugged_monitors true

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a gromit-mpx manage=off
bspc rule -a stalonetray manage=off
bspc rule -a vlc floating=on
bspc rule -a feh floating=on
