#!/bin/sh
# Common stuff for X and Wayland

export LC_ALL=en_US.UTF-8
export PATH="~/.local/bin:$PATH"

# XDG paths
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_RUNTIME_DIR="$HOME/.tmp"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"

# Qt
export QT_QPA_PLATFORM=gtk # https://github.com/CrimsonAS/gtkplatform
#export QT_QPA_PLATFORMTHEME=qt5ct
export QT_STYLE_OVERRIDE=adwaita

# Prevent X errors and glitches
export GDK_SYNCHRONIZE=1
export COGL_ATLAS_DEFAULT_BLIT_MODE=framebuffer

# DRI3 works on FreeBSD drm-next, but isn't enabled by default in the Mesa port
# *Required* for 3D acceleration in Xwayland!
export LIBGL_DRI3_ENABLE=1

# Java GUI crap
export _JAVA_AWT_WM_NONREPARENTING=1
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'

# Firefox touch support
export MOZ_USE_XINPUT2=1

killall evscript
evscript -f ~/.config/evscript.dyon -d /dev/input/event* &
