#!/bin/sh
# Common stuff for X and Wayland

export LC_ALL=en_US.UTF-8
export PATH="~/.local/bin:$PATH"

# XDG paths
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_RUNTIME_DIR="/tmp/$USER"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"

# Prevent X errors and glitches
# export GDK_SYNCHRONIZE=1
# export COGL_ATLAS_DEFAULT_BLIT_MODE=framebuffer

# Java GUI crap
export _JAVA_AWT_WM_NONREPARENTING=1
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'

# Firefox touch support
export MOZ_USE_XINPUT2=1

#killall evscript
#evscript -f ~/.config/evscript.dyon -d /dev/input/event* &
