#!/bin/sh
# This came from Greg V's dotfiles:
#      https://github.com/myfreeweb/dotfiles
# Feel free to steal it, but attribution is nice

if [ "$1" == "start" ]; then
	sleep 0.3
	xvkbd -text "\Cl\Cc" # For some reason this doesn't work with xdotool
	sleep 0.1
	bspc rule -a mpv -o floating=on sticky=on
	mpv $MPV_HWDEC_FLAGS "https://www.youtube.com/embed/`xclip -o | sed -E -e "s/.*v=([^&]+).*/\1/"`" &
	sleep 1
	xdotool search --class mpv windowsize 1280 720
elif [ "$1" == "toggleopacity" ]; then
	transset -t -i "`xdotool search --class mpv`" 0.1
fi
