#!/usr/bin/env zsh

FILENAME=~/Screen_$(date +%F-%T).png
#maim $* $FILENAME
if [[ "$*" == "-s" ]]; then
	read -r G < <(slop -f "%g")
	import -window root -crop $G $FILENAME
else
	import -window root $FILENAME
fi
pngquant --force --ext .png --quality 85-100 $FILENAME
