#!/usr/bin/env ruby
# gem install ruby-dbus
# https://github.com/mvidner/ruby-dbus/pull/57

n = `mixer vol #{ARGV.first}`.match(/to ([0-9]+):/)[1].to_i / 5

require "dbus"

msg = "🔈 #{"+" * n}#{"-" * (20-n)} 🔈"
notification = DBus::SessionBus.instance
                 .service("org.freedesktop.Notifications")
                 .object("/org/freedesktop/Notifications")
notification.introspect
notification["org.freedesktop.Notifications"]
  .Notify("mixer", 99999899999, "", "<span weight='normal' font='13'>#{msg}</span>", "", [], {}, 300)
