#!/bin/sh
# This came from Greg V's dotfiles:
#      https://github.com/myfreeweb/dotfiles
# Feel free to steal it, but attribution is nice

# Need a session bus for stuff like nautilus trash
[ -z "$DBUS_SESSION_BUS_ADDRESS" ] && exec ck-launch-session dbus-launch --sh-syntax --exit-with-session sh $HOME/.xinitrc

# Make sure XCompose works!
export GTK_IM_MODULE=xim QT_IM_MODULE=xim XMODIFIERS="@im=none"

. ~/.desktoprc
# NVIDIA: echo 'export MPV_HWDEC_FLAGS="--hwdec=vdpau"' >> ~/.xinitrc.local
# INTEL:  echo 'export MPV_HWDEC_FLAGS="--vo=vaapi --hwdec=vaapi"' >> ~/.xinitrc.local
. ~/.xinitrc.local
xrdb ~/.Xresources &

# Keyboard setup inspired by http://stevelosh.com/blog/2012/10/a-modern-space-cadet/
xset r rate 300 35
setxkbmap 'us(colemak),ru' \
	-option ctrl:nocaps \
	-option ctrl:lctrl_meta \
	-option compose:ralt \
	-option grp:alt_space_toggle \
	$XKB_OPTS
if [ -x "`which xcape`" ]; then
	xcape -t 350 -e 'Control_L=Escape'
	xcape -t 350 -e 'Shift_L=Shift_L|9'
	xcape -t 350 -e 'Shift_R=Shift_R|0'
fi

# All the things
dunst &
unclutter &
# NVIDIA: echo 'COMPTON_BACKEND_FLAGS="--backend glx --glx-no-stencil --paint-on-overlay --vsync opengl-swc"' >> ~/.xinitrc.local
# INTEL:  echo 'COMPTON_BACKEND_FLAGS="--backend xr_glx_hybrid --vsync opengl-swc"' >> ~/.xinitrc.local
compton -c -o 0.35 -f -D 4 -m 1.0 -i 1.0 -e 1.0 \
	$COMPTON_BACKEND_FLAGS \
	--clear-shadow \
	--shadow-exclude "fullscreen" \
	--shadow-exclude "argb && (override_redirect || wmwin)" \
	--shadow-exclude "class_g = 'slop'" \
	--shadow-exclude "n:e:gromit-mpx" &
redshift -l 55.75:37.616 -t 6500:4200 &
~/.fehbg &
exec i3
