#!/bin/sh
export PATH=~/.local/bin:$PATH
export GTK_IM_MODULE=xim # Makes the Compose key work in GTK

killall ssh-agent
rm -f ~/.ssh/ssh_auth_sock

. ~/.xinitrc.local
. ~/.fehbg
xsetroot -cursor_name left_ptr
xrdb ~/.Xresources &

xset r rate 270 35
xcape -t 350 -e 'Control_L=Escape'
xcape -t 350 -e 'Shift_L=Shift_L|9'
xcape -t 350 -e 'Shift_R=Shift_R|0'
setxkbmap 'us(colemak),ru' \
	-option ctrl:nocaps \
	-option ctrl:lctrl_meta \
	-option compose:ralt \
	-option grp:win_space_toggle

sxhkd &
dunst &
unclutter &
xscreensaver -no-splash &
compton -bc -o 0.35 --shadow-exclude 'n:e:gromit-mpx'
exec bspwm
