(source gnu)
(source melpa)

; General
(depends-on "better-defaults")
(depends-on "smex")
(depends-on "smart-tab")
(depends-on "smartparens")
(depends-on "rainbow-delimiters")
(depends-on "popwin")
(depends-on "diminish")
(depends-on "drag-stuff")
(depends-on "find-file-in-project")

; Usability
(depends-on "evil")
(depends-on "evil-leader")
(depends-on "evil-numbers")
(depends-on "evil-surround")
(depends-on "evil-search-highlight-persist")
(depends-on "evil-terminal-cursor-changer")
(depends-on "powerline-evil")

; Theme
(depends-on "base16-theme")

; Clojure
(depends-on "clojure-mode")
(depends-on "cider")
